---
keywords: fastai
description: Lesson about simulations and what they're used for 
title: 3.16 Lesson
layout: default
toc: true
badges: false
comments: true
categories: [lesson]
nb_path: _notebooks/2022-12-12-Simulations.ipynb
layout: notebook
---

<!--
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: _notebooks/2022-12-12-Simulations.ipynb
-->

<div class="container" id="notebook-container">
        
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="First-Order-of-Business:-Get-your-notebook">First Order of Business: Get your notebook<a class="anchor-link" href="#First-Order-of-Business:-Get-your-notebook"> </a></h1><ul>
<li><p>Open a terminal in vscode, run command: cd _notebooks, type 'wget' and paste this link into said terminal and run it</p>
</li>
<li><p>Take notes wherever you please, but you will be graded on participating</p>
</li>
</ul>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="So,-what-is-a-simulation-anyway?">So, what is a simulation anyway?<a class="anchor-link" href="#So,-what-is-a-simulation-anyway?"> </a></h1><ul>
<li><p>A simulation is a tested scenario used for viewing results/outputs to prepare for them in real world situations</p>
</li>
<li><p>These can be used for games like dice rolling, spinners, etc</p>
</li>
<li><p>These can be used for practical things such as building structures, testing car crashes, and other things before engaging in them in the real world</p>
</li>
<li><p>These simulations can have the option of obeying real world physics (Gravity, collision) or they can go against these norms since this is a fictitious scenario, and couldn't happen in real life</p>
</li>
</ul>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="Big-Question">Big Question<a class="anchor-link" href="#Big-Question"> </a></h1><ul>
<li><p>Which of the following simulations could be the LEAST useful?</p>
</li>
<li><p>A retailer trying to identify which products sold the most</p>
</li>
<li>A restaurant determining the efficiency of robots </li>
<li>An insurance company studying the rain impact of cars </li>
<li>A sports bike company studying design changes to their new bike design </li>
</ul>
<ul>
<li>If you guessed a bike company, you're wrong, because the retail simulation was the right answer. Simulating robots in food service, sudying rain impact on vehicles, and new bike design can contribute a lot more to society in comparison to seeing what products sell more than others. </li>
</ul>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="Next-Big-Question">Next Big Question<a class="anchor-link" href="#Next-Big-Question"> </a></h1><p>If you were making a simulation for making a new train station, which of the following would be true about this simulation?</p>
<ul>
<li>It could reveal potential problems/safety issues before construction starts </li>
<li>It cannot be used to test the train station in different weather </li>
<li>Simulation will add high costs to projects </li>
<li>Simulation is not needed because this train station already exists  </li>
</ul>
<ul>
<li>Potential Saftey was the right answer, because you need somewhere to test the safety and ethicness of what you're about to do before you start building it. Otherwise, let's just say you'll have a special plaque for FBI's Most Wanted</li>
</ul>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="Simulation-1:">Simulation 1:<a class="anchor-link" href="#Simulation-1:"> </a></h1><p>Both programs below do the same thing. Given a height and a weight, they calculate how long it will take for a object to fall to the ground in a vacuum subjected to normal Earth levels of gravity.</p>
<p>However, the second one is a simulation. It calculates the distance the object has fallen every 0.1 seconds. This is useful for if you wanted a visual representation of a falling object, which pure math can't do as smoothly.</p>

</div>
</div>
</div>
    {% raw %}
    
<div class="cell border-box-sizing code_cell rendered">
<div class="input">

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">height</span> <span class="o">=</span> <span class="nb">float</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&quot;height in meters?&quot;</span><span class="p">))</span>

<span class="n">weight</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&quot;weight in pounds?&quot;</span><span class="p">)</span>

<span class="n">stuff</span> <span class="o">=</span> <span class="p">(</span><span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">height</span> <span class="o">/</span> <span class="mf">9.8</span><span class="p">))</span><span class="o">**</span><span class="p">(</span><span class="mi">1</span><span class="o">/</span><span class="mi">2</span><span class="p">)</span>

<span class="nb">print</span><span class="p">(</span><span class="s2">&quot;It will take&quot;</span><span class="p">,</span> <span class="n">stuff</span><span class="p">,</span><span class="s2">&quot;seconds for an object that weighs&quot;</span><span class="p">,</span><span class="n">weight</span><span class="p">,</span><span class="s2">&quot;pounds&quot;</span><span class="p">,</span><span class="s2">&quot;to fall &quot;</span><span class="p">,</span><span class="n">height</span><span class="p">,</span><span class="s2">&quot;meters in a vacuum&quot;</span><span class="p">)</span>
</pre></div>

    </div>
</div>
</div>

</div>
    {% endraw %}

    {% raw %}
    
<div class="cell border-box-sizing code_cell rendered">
<div class="input">

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">t</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">g</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">d</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">false</span> <span class="o">=</span> <span class="kc">True</span>
<span class="k">while</span> <span class="n">false</span><span class="p">:</span>
    <span class="n">t</span> <span class="o">=</span> <span class="n">t</span> <span class="o">+</span> <span class="mf">0.1</span>
    <span class="n">d</span> <span class="o">=</span> <span class="mf">9.8</span> <span class="o">/</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">t</span><span class="o">**</span><span class="mi">2</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">d</span> <span class="o">&gt;=</span> <span class="n">height</span><span class="p">:</span>
        <span class="n">false</span> <span class="o">=</span> <span class="kc">False</span>
    <span class="c1">#print(d) # if you want to print the distance every time it calculates it. Too long to output to a terminal, but this could be useful to display graphically. </span>
    <span class="c1">#print(t)</span>

<span class="nb">print</span><span class="p">(</span><span class="n">t</span><span class="p">)</span>
<span class="nb">print</span><span class="p">(</span><span class="n">d</span><span class="p">)</span>
</pre></div>

    </div>
</div>
</div>

</div>
    {% endraw %}

<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="Simulation-2:">Simulation 2:<a class="anchor-link" href="#Simulation-2:"> </a></h1><ul>
<li><p>This simulation is made in order to simulate movement on a 2d plane vs a 3d plane.</p>
</li>
<li><p>How it works: we have multiple variables, if statements and equations under a while command in order to randomy generate steps on a 2d plane. Once it reaches the set destination, it will say that the man made it home after x amount of steps.</p>
</li>
<li><p>For the 3D plane, it takes a lot longer due to how big and open the 3d environment is, so there are more if statements in the 3d plane</p>
</li>
</ul>
<p>(explain further)</p>

</div>
</div>
</div>
    {% raw %}
    
<div class="cell border-box-sizing code_cell rendered">
<div class="input">

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="kn">import</span> <span class="nn">random</span>
<span class="n">x</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">y</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">nights</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">stopped</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">turns</span> <span class="o">=</span> <span class="p">[]</span>

<span class="k">while</span> <span class="p">(</span><span class="n">nights</span> <span class="o">&lt;</span> <span class="mi">100</span><span class="p">):</span>
    <span class="n">step</span> <span class="o">=</span> <span class="n">random</span><span class="o">.</span><span class="n">randrange</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="n">x</span><span class="o">+</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">1</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="n">x</span><span class="o">-</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">2</span><span class="p">:</span>
        <span class="n">y</span> <span class="o">=</span> <span class="n">y</span><span class="o">+</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">3</span><span class="p">:</span>
        <span class="n">y</span> <span class="o">=</span> <span class="n">y</span><span class="o">-</span><span class="mi">1</span>

    <span class="n">turn</span> <span class="o">=</span> <span class="n">turn</span> <span class="o">+</span> <span class="mi">1</span>

    <span class="k">if</span> <span class="n">x</span> <span class="o">==</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">y</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="n">nights</span> <span class="o">=</span> <span class="n">nights</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;The Man Has Made It Home After &quot;</span><span class="p">,</span> <span class="n">turn</span><span class="p">,</span> <span class="s2">&quot;Turns&quot;</span><span class="p">)</span>
        <span class="n">turns</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">turn</span><span class="p">)</span>
        <span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="k">if</span> <span class="n">turn</span><span class="o">/</span><span class="mi">1000</span> <span class="o">%</span> <span class="mi">1000</span> <span class="o">==</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span> <span class="o">!=</span> <span class="mi">0</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;(&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">,</span> <span class="s2">&quot;)&quot;</span><span class="p">)</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">turn</span> <span class="o">&gt;</span> <span class="mi">10000000</span><span class="p">):</span>
        <span class="n">stopped</span> <span class="o">=</span> <span class="n">stopped</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">y</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">nights</span> <span class="o">=</span> <span class="n">nights</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Caped&quot;</span><span class="p">)</span>

<span class="n">average</span> <span class="o">=</span> <span class="nb">sum</span><span class="p">(</span><span class="n">turns</span><span class="p">)</span> <span class="o">/</span> <span class="nb">len</span><span class="p">(</span><span class="n">turns</span><span class="p">)</span>
<span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Avaerage&quot;</span><span class="p">,</span> <span class="n">average</span><span class="p">,</span> <span class="s2">&quot;Ones that when&#39;t too long &quot;</span><span class="p">,</span> <span class="n">stopped</span><span class="p">)</span>
</pre></div>

    </div>
</div>
</div>

</div>
    {% endraw %}

    {% raw %}
    
<div class="cell border-box-sizing code_cell rendered">
<div class="input">

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="kn">import</span> <span class="nn">random</span>
<span class="n">x</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">y</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">z</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">nights</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">stopped</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">turns</span> <span class="o">=</span> <span class="p">[]</span>

<span class="k">while</span> <span class="p">(</span><span class="n">nights</span> <span class="o">&lt;</span> <span class="mi">100</span><span class="p">):</span>
    <span class="c1">#rando movement</span>
    <span class="n">step</span> <span class="o">=</span> <span class="n">random</span><span class="o">.</span><span class="n">randrange</span><span class="p">(</span><span class="mi">6</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="n">x</span><span class="o">+</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">1</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="n">x</span><span class="o">-</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">2</span><span class="p">:</span>
        <span class="n">y</span> <span class="o">=</span> <span class="n">y</span><span class="o">+</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">3</span><span class="p">:</span>
        <span class="n">y</span> <span class="o">=</span> <span class="n">y</span><span class="o">-</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">4</span><span class="p">:</span>
        <span class="n">z</span> <span class="o">=</span> <span class="n">z</span><span class="o">+</span><span class="mi">1</span>
    <span class="k">if</span> <span class="n">step</span> <span class="o">==</span> <span class="mi">5</span><span class="p">:</span>
        <span class="n">z</span> <span class="o">=</span> <span class="n">z</span><span class="o">-</span><span class="mi">1</span>
    <span class="c1">#Turn counter</span>
    <span class="n">turn</span> <span class="o">=</span> <span class="n">turn</span> <span class="o">+</span> <span class="mi">1</span>
    <span class="c1">#Goal check</span>
    <span class="k">if</span> <span class="n">x</span> <span class="o">==</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">y</span> <span class="o">==</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">z</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="n">nights</span> <span class="o">=</span> <span class="n">nights</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;The Bird Has Made It Home After &quot;</span><span class="p">,</span> <span class="n">turn</span><span class="p">,</span> <span class="s2">&quot;Turns&quot;</span><span class="p">)</span>
        <span class="n">turns</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">turn</span><span class="p">)</span>
        <span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="k">if</span> <span class="n">turn</span><span class="o">/</span><span class="mi">1000</span> <span class="o">%</span> <span class="mi">1000</span> <span class="o">==</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span> <span class="o">+</span> <span class="n">z</span> <span class="o">!=</span> <span class="mi">0</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;(&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">,</span> <span class="s2">&quot;) &quot;</span><span class="p">,</span><span class="s2">&quot;| &quot;</span><span class="p">,</span> <span class="n">z</span><span class="p">)</span>
    <span class="c1">#Too long Stoper</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">turn</span> <span class="o">&gt;</span> <span class="mi">10000000</span><span class="p">):</span>
        <span class="n">stopped</span> <span class="o">=</span> <span class="n">stopped</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="n">turn</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">y</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">z</span> <span class="o">=</span> <span class="mi">0</span>
        <span class="n">nights</span> <span class="o">=</span> <span class="n">nights</span> <span class="o">+</span> <span class="mi">1</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Caped&quot;</span><span class="p">)</span>

<span class="n">average</span> <span class="o">=</span> <span class="nb">sum</span><span class="p">(</span><span class="n">turns</span><span class="p">)</span> <span class="o">/</span> <span class="nb">len</span><span class="p">(</span><span class="n">turns</span><span class="p">)</span>
<span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Avaerage&quot;</span><span class="p">,</span> <span class="n">average</span><span class="p">,</span><span class="s2">&quot;Ones that when&#39;t too long &quot;</span><span class="p">,</span> <span class="n">stopped</span><span class="p">)</span>
</pre></div>

    </div>
</div>
</div>

</div>
    {% endraw %}

<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="Simulations-in-the-wild">Simulations in the wild<a class="anchor-link" href="#Simulations-in-the-wild"> </a></h1><p>Simulations are used extremely frequently in real life applications. One of the most common examples of simulations are video games. A games physics engine can accurately simulate objects colliding</p>
<p>Another example is Blender, the software used in 3d animations class, here at Del Norte. Blender is made up of many small simulations, but one big one it uses is simulating the way light bounces off of and interacts with objects.</p>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered"><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h1 id="HW-!!!">HW !!!<a class="anchor-link" href="#HW-!!!"> </a></h1><p>Create a simulation. It can be anything, just has to simulate something.</p>
<p>Some ideas:</p>
<ul>
<li>Two objects colliding</li>
<li>Gravity on other planets</li>
</ul>
<p>AND</p>
<p>Find an example of a simulation in a software/game you use, screenshot, and explain how it is a simulation</p>

</div>
</div>
</div>
</div>
 

